apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: rhdhpai802-8
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rh-ee-lyoon/rhdhpai802-8:38146147769056e933cbb4ee510128be0edabd52@sha256:5f04aa535fb52dcc93bab95f734f4e560a575cbc47dc364c4efd36c6005be39d # use pre-built to bootstrap
          name: app-inference
